# Generated by Django 2.0.5 on 2018-05-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180524_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagefiles',
            new_name='image',
        ),
    ]
